# Generated by Django 5.1 on 2024-09-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
